spec-version: 0.30.0
name: preql
version: 0.1
synopsis: PostgreSQL library focused on Quasiquoters
description: exploring type-safe SQL queries using standard Postgres syntax
category: Database, PostgreSQL
github: bergey/preql
author: Daniel Bergey
maintainer: bergey@teallabs.org

library:
  source-dirs: [src]

tests:
  tests:
    source-dirs: test
    main: Test.hs
    dependencies:
      - preql
      - bytestring
      - postgresql-libpq
      - tasty
      - tasty-hunit
      - text
      - uuid
      - vector

build-tools:
  - alex
  - happy
      
dependencies:
    - aeson
    - array
    - base
    - binary-parser
    - bytestring
    - bytestring-strict-builder
    - contravariant
    - free
    - mtl
    - postgresql-binary
    - postgresql-libpq
    - syb
    - template-haskell
    - text
    - th-lift-instances
    - time
    - transformers
    - uuid
    - vector

default-extensions:
  - OverloadedStrings
