spec-version: 0.30.0
name: preql
version: 0.4
synopsis: safe PostgreSQL queries using Quasiquoters
description: |
  Before you Post(gres)QL, preql.

  @preql@ provides a low-level interface to PostgreSQL and a quasiquoter that converts
  inline variable names to SQL parameters.  Higher-level interfaces, checking SQL syntax &
  schema, are planned.

  the [quickstart](https://github.com/bergey/preql#quickstart) 
  or the [vision](https://github.com/bergey/preql#vision-parsing-sql-in-haskell-quasiquotes)

  Most applications will want to import the top-level module @Preql@.  When writing @SQL@
  instances or your own higher-level abstractions, you may want the lower-level,
  IO-specific functions in @Preql.Wire@, not all of which are re-exported from @Preql@.
    
category: Database, PostgreSQL
github: bergey/preql
author: Daniel Bergey
maintainer: bergey@teallabs.org
extra-doc-files:
  - CHANGELOG.md

library:
  source-dirs: [src]

tests:
  tests:
    source-dirs: test
    main: Test.hs
    dependencies:
      - preql
      - generic-random >= 1.3.0.1 && < 1.3.1
      - QuickCheck >= 2.13.2 && < 2.14.3
      - tasty >= 1.2.3 && < 1.4.1
      - tasty-hunit >= 0.10.0 && < 0.10.1
      - hedgehog
      - tasty-hedgehog

build-tools:
  - alex
  - happy
      
dependencies:
  - aeson >= 1.4.7.1 && < 1.5.5
  - array >= 0.5.4.0 && < 0.5.5
  - base >= 4.13.0.0 && < 4.15
  - binary-parser >= 0.5.6 && < 0.6
  - bytestring >= 0.10.10.0 && < 0.10.11
  - bytestring-strict-builder >= 0.4.5.3 && < 0.4.6
  - contravariant >= 1.5.2 && < 1.5.3
  - free >= 5.1.3 && < 5.1.5
  - mtl >= 2.2.2 && < 2.2.3
  - postgresql-binary >= 0.12.2 && < 0.12.4
  - postgresql-libpq >= 0.9.4.3 && < 0.9.5
  - scientific >= 0.3.6.2 && < 0.3.7
  - syb >= 0.7.1 && < 0.7.2
  - template-haskell >= 2.15.0.0 && < 2.17
  - text >= 1.2.3.2 && < 1.2.5
  - th-lift-instances >= 0.1.18 && < 0.1.19
  - time >= 1.9.3 && < 1.9.4
  - transformers >= 0.5.6.2 && < 0.5.7
  - uuid >= 1.3.13 && < 1.3.14
  - vector >= 0.12.1.2 && < 0.12.2
  - vector-sized >= 1.4.2 && < 1.4.3

default-extensions:
  - OverloadedStrings
  - DataKinds
