name: Haskell CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
  schedule:
    - cron: "30 4 * * 2"

jobs:
  container--job:
    runs-on: ubuntu-latest
    container: ubuntu-latest

    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_PASSWORD: postgres

  build:
    strategy:
      matrix:
        plan:
          - { build: stack, resolver: "" }
          - { build: stack, resolver: "--resolver lts-14" } # GHC 8.6
          - { build: stack, resolver: "--resolver lts-12" } # GHC 8.4


    steps:
    - uses: actions/checkout@v2
    # - uses: actions/setup-haskell@v1
      # with:
      #   ghc-version: '8.8.3'
      #   cabal-version: '3.0'
    - name: Install dependencies
      run: |
        stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
      env:
        ARGS: ${{ matrix.plan.resolver }}
    - name: Build
      run: |
        stack --no-terminal $ARGS test --no-run-tests --bench --no-run-benchmarks --haddock --no-haddock-deps
      env:
        ARGS: ${{ matrix.plan.resolver }}
    - name: Run tests
      run: stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      env:
        PREQL_TEST_DB: postgres
        PGHOST: postgres
        PGPASSWORD: postgres
