name: Haskell CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
  schedule:
    - cron: "30 4 * * 2"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        plan:
          - { build: stack, resolver: "" }
          - { build: stack, resolver: "--resolver lts-14" } # GHC 8.6
          - { build: stack, resolver: "--resolver lts-12" } # GHC 8.4

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:12.2
        ports: [ "5432:5432" ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    # - uses: actions/setup-haskell@v1
      # with:
      #   ghc-version: '8.8.3'
      #   cabal-version: '3.0'
    - name: Install dependencies
      run: |
        stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
      env:
        ARGS: ${{ matrix.plan.resolver }}
    - name: Build
      run: |
        stack --no-terminal $ARGS test --no-run-tests --bench --no-run-benchmarks --haddock --no-haddock-deps
      env:
        ARGS: ${{ matrix.plan.resolver }}
    - name: Run tests
        run: stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      env:
        PREQL_TEST_DB: postgres
